apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.frontend.name }}"
  labels:
    app: "{{ .Values.frontend.name }}"
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        app: {{ .Values.frontend.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: "{{ .Values.frontend.name }}"
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.service.internalPort }}
          env:
            - name: POSTGRES_CONN_STR
              value: {{ .Values.postgresConnString | quote }}
            - name: FRONT_END_PORT
              value: "{{ .Values.frontend.service.internalPort }}"
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}

