{{- if .Values.frontend.ingress.enabled }}
{{- $frontendServiceName := .Values.frontend.name -}}
{{- $frontendPort := .Values.frontend.service.internalPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.frontend.name }}-ingress
  labels:
    app: {{ .Values.frontend.name }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    release: {{ .Release.Name | quote }}
  annotations:
    {{- if .Values.frontend.ingress.tls }}
    ingress.kubernetes.io/secure-backends: "true"
    {{- end }}
    {{- range $key, $value := .Values.frontend.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range .Values.frontend.ingress.hosts }}
      - host: {{ . }}
        http:
          paths:
            - backend:
                serviceName: {{ $frontendServiceName }}
                servicePort: {{ $frontendPort }}
    {{- end }}
{{- if .Values.frontend.ingress.tls }}
  tls:
  {{- range .Values.frontend.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
{{- end }}
